### ISSUE TITLE
Bug: Create Custom privilege DHS/Azure is not working.

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/cloud-enablement-azure#33]
Environment - DHS/Azure. Attached screen shot shows all the roles 'testuser' has. 

Query Console code for creating privilege fails. 
Code:
--
'use strict';

// execute this against the security database

declareUpdate();   
const sec = require('/MarkLogic/security.xqy');
   
sec.createPrivilege("mypriv", 
                     "http://marklogic.com/xdmp/privileges/mypriv", 
                     "execute", 
                     "Developer")

// Creates an execute privilege, named "mypriv," and assigns it to the "Developer" role. 
---
Failure message: 
--
[javascript] SEC-PRIV: xdmp:security-assert("http://marklogic.com/xdmp/privileges/create-privilege", "execute") -- Need privilege: http://marklogic.com/xdmp/privileges/create-privilege
--
Code executed via SoapUI. 
Post: https://xqajd70xq.z.marklogicsvc.com:8003/manage/v2/privileges
{
              "privilege-name": "test-priv",
              "action": "http://marklogic.com/xdmp/privileges/rest-reader",
              "kind": "execute"
}

Failure message:
{"errorResponse": {
   "statusCode": "403",
   "status": "Forbidden",
   "messageCode": "",
   "message": "You do not have credentials to access /manage/v2/privileges ."
}}
---
<img width="968" alt="Screen Shot 2020-06-17 at 9 11 48 AM" src="https://user-images.githubusercontent.com/51504744/84911316-9b3ba780-b07d-11ea-9c90-84c4fc6179cd.png">

**Comment by ryanjdew** [comment]
@sundarbandepalli The creation of custom privileges in the DHS/Azure environment is restricted to a set domain as defined in the "User and Roles" section of the Data Hub documentation site.

"A custom execute privilege must be assigned an action starting with http://datahub.marklogic.com/custom/."  https://docs.marklogic.com/datahub/security/users-and-roles.html

**Comment by sundarbandepalli** [comment]
To recap. The custom privilege has to be in the "http://datahub.marklogic.com/custom/" namespace.
 
The following code via SoapUI works. However, create privilege via query console does not work.
 
{
   "privilege-name": "test-priv",
   "action": "http://datahub.marklogic.com/custom/mypriv",
   "kind": "execute"
}
 
I will close out 33.

**Comment by sundarbandepalli** [comment]
Close.
